services:
  laravel-docker:
    image: ghcr.io/jay19240-teaching/cda-api-prod:latest
    ports:
      - 8000:80

  vue-docker:
    image: ghcr.io/jay19240-teaching/cda-spa-prod:latest
    ports:
      - 80:80

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email julien.rog24@gmail.com -d pokedex.blog --agree-tos

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306