services:
  laravel-docker:
    image: docker pull ghcr.io/jay19240-teaching/cda-api:latest
    container_name: laravel-docker
    ports:
      - 8000:80

  vue-docker:
    image: docker pull ghcr.io/jay19240-teaching/cda-spa:latest
    container_name: vue-docker
    ports:
      - 80:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306