services:
  laravel-docker:
    image: ghcr.io/jay19240-teaching/cda-api:latest
    ports:
      - 8000:80

  vue-docker:
    image: ghcr.io/jay19240-teaching/cda-spa:latest
    environment:
      VITE_API_BASE: "http://12.12.12.12"
    ports:
      - 80:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306