services:
  laravel-docker:
    container_name: laravel-docker
    build: ./Cursus-api


  vue-docker:
    container_name: vue-docker
    build: ./Cursus-spa

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - 3306:3306