name: pokedex-app

on: # specify the build to trigger the automated ci/cd
  push:
    branches:
      - "main"
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./Cursus-api
          push: true
          tags: |
            ghcr.io/jay19240/cda-api:latest
            ghcr.io/jay19240/cda-api:${{ github.sha }}

  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Tests-api
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Docker
      uses: hoverkraft-tech/compose-action@v2.0.1
    - name: Sleep for 10 seconds
      run: sleep 10s
      shell: bash
    - name: Database migrate
      run: docker exec laravel-docker bash -c "php artisan migrate"
    - name: Database seeding
      run: docker exec laravel-docker bash -c "php artisan db:seed"
    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm run test